FROM golang:1.23

RUN apt-get update && apt-get install -y \
    protobuf-compiler \
    graphviz \
    && go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest \
    && apt-get clean

WORKDIR /host
